
# sample file
sample_file: "/home/bayraktar/PycharmProjects/Fungi_methylation_calling/snakemake/workflow/samples.csv"

# results are stored here
results: "results"

# Windows size for weighted methylation score calculation
window_size: 10000

# Minimal coverage for a base
min_cov: 4

# Tab seperated file containing names of chromosomes and their sizes
chromosome_sizes: "/home/bayraktar/PycharmProjects/Fungi_methylation_calling/snakemake/test_data/chrom_size.txt"

# The reference genome
genome: "/home/bayraktar/PycharmProjects/Fungi_methylation_calling/snakemake/test_data/verdahJR2.pilon6.fa"

# Genes BED
genes: "/home/bayraktar/PycharmProjects/Fungi_methylation_calling/snakemake/test_data/genes.bed"

# TE & repeats
repeats: "/home/bayraktar/PycharmProjects/Fungi_methylation_calling/snakemake/test_data/TE.bed"


