
# sample file
sample_file: "Fungi_methylation_calling/snakemake/workflow/samples.csv"

# results are stored here
results: "results"

# Windows size for weighted methylation score calculation
window_size: 10000

# Minimal read coverage
min_cov: 4

# Tab seperated file containing names of chromosomes and their sizes
chromosome_sizes: "Fungi_methylation_calling/snakemake/workflow/data/chrom_size.txt"

# The reference genome
genome: "Fungi_methylation_calling/snakemake/workflow/data/verdahJR2.pilon6.fa"

# Gene annotation in BED format
genes: "Fungi_methylation_calling/snakemake/workflow/data/genes.bed"

# TE & repeat annotation in BED format
repeats: "Fungi_methylation_calling/snakemake/workflow/data/TE.bed"


